language: go

sudo: false

matrix:
  include:
    - go: 1.x
      env:
        - RELEASE=true
        - GO111MODULE=on
    - go: master
      env:
        - RELEASE=false
        - GO111MODULE=on
  allow_failures:
    - go: master

after_success:
  - go build -ldflags="-s -w"

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: NF3Miv7Onw0rG6aPHW0Bnq2LasDkjoSv8zZUdU8UKntAflwSC1NV84ExLv2K5M0yIyV5lOYKBgHvzIuJqq+0NgheKaSQuyl825VR48IXqEfMhoOFF+qZkdOTmKO2FLRyTT07tWqFPE9iPUhO5ktkXUtwKc0BQyzaJgc/OH//mqzCHqRivmMIgv4cROWvBHzVHFfhv2ZSL5Fcjoypsqm6svgRhDrWUrBuofSYzrafYPCfo9e0LEGlevU+gTSMoEH+cM+Cx1MTfmUfzjmd8egaCn6IwstvdQj4JA8X1kk5lflwRAtQo5EmDV3uskc1tdTBmRd2qWxT4z+Fq0MefhKWfwzykByPeC1SXH4+lFHLF57cM2D0WkLVPClI+U1VupGr5ZO/iasHm//gMqPdOwjKK/h2uugeC6mRDNSPdFNV43OGzSiuc++R5Mh5jVrkGLc9JVrmeke8UroQYPc9CsfgvOvbyhubk5aH3SUea3xYshu0eurds6zbawTCZA5QYxBsCkPG8BqcLZACL4wfxb558VmixyCB/YiF65IrYV+2c3BolHO/Xx8SBf8muyX3M5MER3NEK4ZRr5MpAoS9hP0da7nCvWAOl0JxM3g5Qpzx4RlT6pZVDqwDtfkxrbcuoip7F4BhodSE3dgYnHpRDwa8ZCQduJiDSPjVQAx1p8iHFMk=
  file: simple-file-server
  on:
    tags: true
    repo: mback2k/simple-file-server
    condition: $RELEASE = true
